print('=' * 50)
print('Desafio 5 = Antecesor e Sucessor de um Número')
print('=' * 50)
print('Digite um numero: ')
n = int(input())
print()
print('O antecessor de {} é o {} e o seu sucessor é o {}'.format(n, n-1, n+1))
print()
print('Fim do desafio 5')